### ISSUE TITLE
IronWorker Overview - "nothing special" + other text edicts

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#149]
1) First sentence you hit on Overview implies that IronWorker is not special. Can we rephrase that to say that it's a standard Linux sandbox. 
1. Write Your Worker
   IronWorker's environment is nothing special—it's just a Linux sandbox that your task is executed in.

2) The A's in the steps stand out a bit. do we need them?

3) &'s bug me

**Comment by paddycarver** [comment]
Sure.

**Comment by frommww** [comment]
4)  underline on "and its dependencies" . confused by the underline. if it remains them maybe not include the "and"

5) "exhaustive" should be changed. makes it sound like torture.  Ironworker should be made to be simple.

6) Can we combine Queue and Schedule into step 3 so we only have 4 steps. I like the progression but don't like 5 steps. makes it seem more difficult that it is. Also puts Queue and Schedule in a line (i know I'm touching on chad's issue of numbering vs not number).

**Comment by frommww** [comment]
The text in boxes should probably not be centered. Left-justified probably better.

**Comment by paddycarver** [comment]
4) meant to emphasise that _all_ dependencies need to be packaged. If said aloud, the "and" would be emphasised, too, so I'm hesitant to remove the emphasis on that part alone. What if I switch to bold? Does that work?

5) Updated.

6) I'm... Hm. On one hand, I think this may be a good idea. On the other, it doesn't call attention to the feature. I don't want people inserting links in the sidebar or slapping in quick fixes to call attention to something later, because it often ends up looking grafted on. Should we change the title to something like "Queue/Schedule" or something?

**Comment by paddycarver** [comment]
Not sure what "the text in boxes" refers to.
