### ISSUE TITLE
Worker: Configuration page

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#160]
- token first than project ID.  (keep consistent that way so it provides conceptual ease)

Opening paragraph.

Change from: 
In the interest of letting users stop writing increasingly lengthy configuration files and start writing code, the maintainers of Iron.io's official client libraries have developed a global configuration scheme for all of Iron.io's services. This lets you set your project ID and token once to make them available across all of Iron.io's services, and even across workspaces. The authors took care to provide a scheme that would allow users the flexibility to set a default, then override it at the service, workspace, or client level.

To something more direct at the onset:

Many of the client libraries make use of a global configuration scheme for all of Iron.io services. This approach lets you set and manage your tokens and project IDs in a centralized manner and make them available across all of Iron.io's services -- even across workspaces. 

It also means you spend less time on configuration issues and more on writing code. This approach also supports the design pattern that calls for strict separation of configuration information from application code.

http://www.12factor.net/config

**Comment by frommww** [comment]
Can we put the  .iron.json   names in the body type in code syntax instead of in quotes?

**Comment by frommww** [comment]
The file hierarchy should probably be Config Hierarchy and seems like it should have the four or five approaches
- .iron.json in .
- iron.json in worker file
- environment variables
- CLI inclusion
- code inclusion

Seems like this should appear nearer the top before the Global Hierarchy (which could probably stand some renaming).

The initial bullet list should be short. Just the name of the file and location and then bulleted notes can provide more detail. This supports better scanning and understanding.

**Comment by frommww** [comment]
I'd really like to see the incode method of config in here. I know it's not recommended and we can bring that out but it can help people understand how things work as well as help with simple examples or special needs that we can't foresee. We can note that it's not recommended because it violates the pattern on separating of config from code.

**Comment by frommww** [comment]
In Accepted Values Section, token/project_id should be first.

token
project_id 
...

Also, should we include sections Necessary and Optional?

**Comment by frommww** [comment]
Should we include an errors section in here that explains what happens when you have bad token or bad project_id. Can mention in passing that error messages are purposely spartan as a security measure.

**Comment by paddycarver** [comment]
First two: good points.

Third: the entire thing is a config hierarchy. Why do files get that title to the exclusion of environment variables, in-code variables, etc.? Not sure you understood the scheme being used here. Tired at the moment, will make an attempt at explaining it tomorrow, as clearly I didn't do a good enough job in the page.

Fourth: I left it out for the following reason: what language should I use? Which library for that language? Which option of that library of that language?

Fifth: Yes on token and project_id, no on necessary and optional. Necessary/optional makes people unsure whether it's necessary at _every_ level or not. All the client libraries give them a pretty good error message if one's not set.

Sixth: I vote no. Because: what happens for which language? Which library? What errors? Should we update it with every change to the library?
