### ISSUE TITLE
IronMQ Client Libs need to be more discoverable

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#162]
I think this is an important "jump to" link....

**Comment by paddycarver** [comment]
Updated title to what I think is a more reasonable solution.

The sidemenu can't become our dumping ground for content we think needs to be more prominent, or it will be useless. I spent a lot of time carefully trimming it down, so I want to consider things carefully before deciding they deserve a link in that sidemenu.

Client libs are currently a hard nut to crack. I like how they're handled in Worker (though they could stand to be brought out a bit more in the language pages) because they're linked to from the first place you'd think to look for them, but it's not simply a landing page of six links to Github.

Cache's libraries page is something I'd like to remove in the future, and work the links into the content in a more meaningful way. It looks really bad to just have a page that consists entirely of a short list of links.

MQ needs a solution like this, too. I'm going to continue thinking on the best way to do this.

**Comment by paddycarver** [comment]
God I hate everything about the current client libraries situation on Cache, and MQ is even worse, as it's not even a list of links that's easy to find.

OK, going to figure out what to do about this.

**Comment by carimura** [comment]
OK let me be more clear with what I was trying to say.... forget the fact that I said client libraries. I get to IronWorker, I glance over the getting started, then I click on my language

The same should happen for IronMQ - except - uh oh, I don't see my language anywhere!

**Comment by paddycarver** [comment]
Yeah. I just... what would we put on each language's page? :-/

I think the ideal solution for this is to do a version of the language switcher on steroids for the overview page. Does that make sense? Then we can include the library link in the overview page, right front and center (where it should be).

**Comment by carimura** [comment]
Sure that would work too. The page just looks very Ruby centric with no clear indication of flow if you aren't a Ruby developer.

Thanks.
