### ISSUE TITLE
Bring out dot-worker

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#172]
Should sprinkle references to dot-worker (for .worker files) around the Dev Center to ease the confusion. Recommended phrase was `.worker (pronounced "dot-worker")`, but obviously should be varied lightly to make it seem less heavy-handed.

**Comment by paddycarver** [comment]
Files to update:

./_includes/sidemenu_worker.html
./_posts/2012-05-31-solutions-image-processing.md
./partner_docs/heroku_worker.md
./worker/index.html
./worker/languages/go/index.md
./worker/languages/java/index.md
./worker/languages/nodejs/index.md
./worker/languages/php/index.md
./worker/languages/ruby/index.md
./worker/languages/ruby/merging-files-and-dirs/index.md
./worker/languages/ruby/merging-gems/index.md
./worker/reference/cli/index.md
./worker/reference/dotworker/index.md
./worker/reference/index.html

**Comment by frommww** [comment]
Paddy 
Here's a customer use case showing some of the confusion:

AlexS
some helpful information about .worker files: http://dev.iron.io/worker/reference/dotworker/

Customer
my .worker now has

runtime "php"
exec "worker.php"

file "iron_mq.phar"
file "iron.json"
but

------> Uploading code package 'worker'
        No exec specified
...
ideas
?

AlexS
ls -la current directory

Customer
ls -la
total 80
drwxr-xr-x   Spire\Domain Users   238B 18 Sep 14:56 ./
drwxr-xr-x   Spire\Domain Users   442B 18 Sep 14:46 ../
-rw-r--r--     Spire\Domain Users    71B 18 Sep 14:55 .worker
-rw-r--r--     Spire\Domain Users    79B 18 Sep 14:53 iron.json
...

AlexS
rename .worker -> worker_name.worker

Customer
oh

KenF
an occasional mistake we're trying to make more clear. mostly our bad.

Customer
yeah, easily confued
confused
.worker to me is like .bashrc
./   ../     iron.json  iron_mq.phar    queueTest.php   simpleTest.php

AlexS
it's because this page http://dev.iron.io/worker/reference/dotworker/ repeating '.worker' many, many times

Customer
ok, so ill try again
iron.json    iron_mq.phar    queueTest.php   queueTest.worker

**Comment by paddycarver** [comment]
I'll push forward with the proposed change from ".worker" to "worker_name.worker" pretty much everywhere we use .worker. I'll try to be pretty explicit about what it means. Hopefully it helps.

**Comment by frommww** [comment]
Did this happen? In looking at  .worker file on dev center just now, I keep seeing references to .worker not worker_name.worker. I can go either way on .worker vs worker_name.worker as the common refernce but on this page, there should be several references to worker_name.worker as well as some labeling of files in the example. 

http://dev.iron.io/worker/reference/dotworker/

Also can we do some sort of label/caption for the examples that lists out a filename. (Would like to see this throughout dev center to better ground what the files are (iron.json, .worker, worker code, etc.)

example_worker.worker

   runtime "ruby"  
   exec "hello_worker.rb"

**Comment by paddycarver** [comment]
We kept talking about it, and we could never seem to agree upon exactly what should be done. I even had a branch with all the instances changed, at some point.

I think you're right, though. I think the dotworker page, at the very least should be changed. I'll do that today.

As for the other discussion, let's keep that in its own issue: #158. Though I do think that will help mitigate this a lot.

**Comment by frommww** [comment]
I don't know if we need to do wholesale changes throughout the docs but in a few places where we have .worker, we can add a note or a parenthetical that would list out an example (ala hello_worker.worker) or just worker_name.worker. Sort of like a trademark or copyright where you just do it for the first reference.

**Comment by dstaley** [comment]
@paddyforan Since you opened this, I'd like you to close it if pull request #229 solves this issue.
