### ISSUE TITLE
Add link to packaging code on Code Upload section

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#180]
I wasn't able to find any info on what a worker is or what the code package is. 

http://dev.iron.io/worker/reference/api/#upload_a_code_package

Link to: http://dev.iron.io/worker/code/packaging/

**Comment by paddycarver** [comment]
What information would you like to see? None of the packaging code on that page applies anymore, thanks to the CLI.

(Please not that all /code URLs are deprecated. They are not linked to by design. I'm waiting until we don't have any traffic to them for a sustained amount of time before deleting them)

**Comment by treeder** [comment]
All of it, it all still applies. The CLI is just a tool to help make things easier, but users don't have to use the CLI. They can package up their own workers, they can write their own clients, etc.

**Comment by treeder** [comment]
Can you add this link @paddyforan ?

**Comment by paddycarver** [comment]
Working on a "top priority" project for @carimura at the moment. I'll take care of this tomorrow. I'm going to need to edit/restructure/move the page around a bit to make it make sense in the current dev center.

I still don't know where code packaging/uploading stands, in terms of documentation. It seems like I'm being given two contradicting marching orders.

**Comment by treeder** [comment]
Ok, no worries. I'll add it.

**Comment by paddycarver** [comment]
Removing my assignment.
