### ISSUE TITLE
Two new pages: tag list, specific tag article list

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#20]
We need two new pages:

1) a page that lists all the tags

2) a page that takes a tag input and displays all the articles for that tag. If we _have_ to this can be a single page that lists all tags and their respective articles and we can just use an anchor to zip down to that specific tag article list.

**Comment by paddycarver** [comment]
There are three ways to handle point 2.

A) We can use a pre-processor to generate the tag pages, which would allow us to take a tag input and just display all articles for that tag. Pros: tags get displayed in the canonical way, hard for us to screw up on accident. Cons: we now need to run a pre-processor. Not so bad if we set it up as a pre-commit hook.

B) We can do a single page that lists all the tags and use anchors, as you mentioned. Pros: No change in workflow, impossible for us to screw up, 100% automated. Cons: Not the typical way tags are displayed, not as "finished" a look.

C) We can do a page for each tag, much like A, but instead of a pre-processor, we manually add pages for tags as e add them. Pros: Familiar display style, no pre-processor. Cons: Very easy for us to screw up (if we forget to add the page or have a slight variation on tag spelling), very low automation, will probably limit the usefulness of tagging to authors.

My recommendation is that we use B and keep the possibility of switching to A in the future open for discussion.

**Comment by carimura** [comment]
Go with your suggestion. Use page anchors to make it _seem_ like a cleaner page. You know, we could even try some JavaScript trickery to hide and show the proper tag div but that may be risky.
