### ISSUE TITLE
Add list of hosted databases that can be used instead of Heroku's shared database

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#83]
Since people can't connect to it from IronWorker, let's have a list of alternatives and point people to this page whenever someone asks about it.

**Comment by treeder** [comment]
Public chat convo:

```
Jimmy T.
6:26 AM
Before I dive too deep, I'm looking to replace Delayed::Job with IronWorker on Heroku, primarily because of throttling.
Does IronWorker have access to the full Rails environment for my app?
That is, can I do DB stuff just like normal?
(in the workers)
Andrei D.
6:26 AM
1) no
2) no access to shared heroku DB
Jimmy T.
6:27 AM
OK, thanks.
Andrei D.
6:28 AM
1) rails env is limited significantly, we're encouraging people to pass stuff they want as payload
2) this is Heroku hosting limitation
Jimmy T.
6:28 AM
What about a dedicated DB?
Andrei D.
6:29 AM
will work fine, as you'll allow access from outside world
Andrew K.
6:29 AM
we do not limit anything, really
it's heroku who limits access to shared dbs
Jimmy T.
6:30 AM
Makes sense. Thanks, that info helps.
```

**Comment by paddycarver** [comment]
@treeder I'm not sure where we'd put this. I can see what it'd say:

"If you need hosted database storage, we've gathered a few examples for you:
- x
- y
- z"

But I don't know where in dev we'd put this. Any thoughts on that? I'd like to not have a dedicated page about databases, because there's really not _that_ much to say. The things that would be crammed into that article are better suited in other places (e.g., instead of writing a database page, I'd rather have a page about interacting with other services--using max_concurrency, delays, handling failures in the outside services... etc.)

Maybe on that outside services page, we could have a short list of database providers?

**Comment by treeder** [comment]
This may not apply anymore now that Heroku migrated everyone to their postgres service. I believe that's open ya?

**Comment by paddycarver** [comment]
No idea. Will find out.

**Comment by frommww** [comment]
I think we need something about databases in there. Mostly just to answer questions that come up or give people some idea as to whether they're on the right track. 
- connecting to them
- if behind firewalls
- security groups
- good practices (run a number of actions instead of a single action)
- use cache and mq to augment processing. 

Maybe we use stackoverflow to hold a lot of questions but then we need some jumping off point / list / search box for people to go there.

**Comment by paddycarver** [comment]
@frommww I think those things apply to 3rd party APIs and other things outside our environment, too, though. I'm not saying I don't think we should address them, I think we should just kind of be generic about it. I have no issue with using databases as an example, but I'd like the page to apply to more than just databases, because the paradigm and strategies are the same. Something like "Working With Your API, Database, and Other Services" or something.

**Comment by carimura** [comment]
Paddy can you outline the page before writing the content? I'm leaning with Ken that connecting with databases is so fundamental that it needs its own section but I could go either way.

**Comment by paddycarver** [comment]
Sure. Right now, our focus is on the docs for the partners and on improving the overall hygiene of the Dev Center (pruning old pages, etc.), so it will probably be the end of the week or next week before I start mapping this article out.

I could be entirely wrong, and as I start mapping the article out, databases stand out and don't fit in enough that it makes sense to include them. In which case, let's figure out where they make sense. But my gut feeling is that the content for them and APIs will be 99% identical. I'll keep you both apprised, and share mindmaps and drafts with you as I go.

**Comment by paddycarver** [comment]
Would it be possible unassign me from this issue, or close the issue?
